name: Build NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  NET_DIRECTORY: net9.0

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore packages
      run: |
           for s in TodoApi AspNetCoreTodo; do
               dotnet restore $s/$s.sln
           done

    - name: Install Coverlet
      run: dotnet tool install --global coverlet.console

    - name: Build solutions
      run: |
           for s in TodoApi AspNetCoreTodo; do
               dotnet build --configuration Debug --no-restore $s/$s.sln /p:DefineConstants="CI_CONTEXT"
           done

    - name: Testing
      run: |
           coverlet AspNetCoreTodoTest/bin/Debug/${{ env.NET_DIRECTORY }}/AspNetCoreTodoTest.dll --target "dotnet" --targetargs "test AspNetCoreTodoTest/AspNetCoreTodoTest.csproj --no-build --verbosity quiet" --format OpenCover --output aspnetcoretodo.coverage.xml

    - name: Upload coverage to CodeCov
      uses: codecov/codecov-action@v5
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    - name: Archive code coverage results
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-report
        path: ./*.coverage.xml
